services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./apps/api:/app
    command: ./main
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kloudpx
    depends_on:
      - db

  web:
    build:
      context: ./apps/web/kloudpxfe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/kloudpxfe:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - api

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kloudpx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
